const options = ["Size", "Color", "Design"];
const variant = [
  {
    id: 44999039320311,
    title: "small / green / Moon",
    option1: "small",
    option2: "green",
    option3: "Moon",
    sku: "8787901",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - small / green / Moon",
    public_title: "small / green / Moon",
    options: ["small", "green", "Moon"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909318391,
    title: "small / green / Galaxy",
    option1: "small",
    option2: "green",
    option3: "Galaxy",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / green / Galaxy",
    public_title: "small / green / Galaxy",
    options: ["small", "green", "Galaxy"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909351159,
    title: "small / green / Solar System",
    option1: "small",
    option2: "green",
    option3: "Solar System",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / green / Solar System",
    public_title: "small / green / Solar System",
    options: ["small", "green", "Solar System"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909383927,
    title: "small / green / Saturn",
    option1: "small",
    option2: "green",
    option3: "Saturn",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / green / Saturn",
    public_title: "small / green / Saturn",
    options: ["small", "green", "Saturn"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 44999039385847,
    title: "small / yellow / Moon",
    option1: "small",
    option2: "yellow",
    option3: "Moon",
    sku: "8787903",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / yellow / Moon",
    public_title: "small / yellow / Moon",
    options: ["small", "yellow", "Moon"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909416695,
    title: "small / yellow / Galaxy",
    option1: "small",
    option2: "yellow",
    option3: "Galaxy",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - small / yellow / Galaxy",
    public_title: "small / yellow / Galaxy",
    options: ["small", "yellow", "Galaxy"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909449463,
    title: "small / yellow / Solar System",
    option1: "small",
    option2: "yellow",
    option3: "Solar System",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / yellow / Solar System",
    public_title: "small / yellow / Solar System",
    options: ["small", "yellow", "Solar System"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909482231,
    title: "small / yellow / Saturn",
    option1: "small",
    option2: "yellow",
    option3: "Saturn",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / yellow / Saturn",
    public_title: "small / yellow / Saturn",
    options: ["small", "yellow", "Saturn"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909514999,
    title: "small / red / Moon",
    option1: "small",
    option2: "red",
    option3: "Moon",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / red / Moon",
    public_title: "small / red / Moon",
    options: ["small", "red", "Moon"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909547767,
    title: "small / red / Galaxy",
    option1: "small",
    option2: "red",
    option3: "Galaxy",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / red / Galaxy",
    public_title: "small / red / Galaxy",
    options: ["small", "red", "Galaxy"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909580535,
    title: "small / red / Solar System",
    option1: "small",
    option2: "red",
    option3: "Solar System",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - small / red / Solar System",
    public_title: "small / red / Solar System",
    options: ["small", "red", "Solar System"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909613303,
    title: "small / red / Saturn",
    option1: "small",
    option2: "red",
    option3: "Saturn",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - small / red / Saturn",
    public_title: "small / red / Saturn",
    options: ["small", "red", "Saturn"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 44999039549687,
    title: "medium / yellow / Moon",
    option1: "medium",
    option2: "yellow",
    option3: "Moon",
    sku: "8787907",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - medium / yellow / Moon",
    public_title: "medium / yellow / Moon",
    options: ["medium", "yellow", "Moon"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909744375,
    title: "medium / yellow / Galaxy",
    option1: "medium",
    option2: "yellow",
    option3: "Galaxy",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - medium / yellow / Galaxy",
    public_title: "medium / yellow / Galaxy",
    options: ["medium", "yellow", "Galaxy"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909777143,
    title: "medium / yellow / Solar System",
    option1: "medium",
    option2: "yellow",
    option3: "Solar System",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - medium / yellow / Solar System",
    public_title: "medium / yellow / Solar System",
    options: ["medium", "yellow", "Solar System"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909809911,
    title: "medium / yellow / Saturn",
    option1: "medium",
    option2: "yellow",
    option3: "Saturn",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - medium / yellow / Saturn",
    public_title: "medium / yellow / Saturn",
    options: ["medium", "yellow", "Saturn"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909842679,
    title: "medium / red / Moon",
    option1: "medium",
    option2: "red",
    option3: "Moon",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - medium / red / Moon",
    public_title: "medium / red / Moon",
    options: ["medium", "red", "Moon"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909875447,
    title: "medium / red / Galaxy",
    option1: "medium",
    option2: "red",
    option3: "Galaxy",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - medium / red / Galaxy",
    public_title: "medium / red / Galaxy",
    options: ["medium", "red", "Galaxy"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909908215,
    title: "medium / red / Solar System",
    option1: "medium",
    option2: "red",
    option3: "Solar System",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - medium / red / Solar System",
    public_title: "medium / red / Solar System",
    options: ["medium", "red", "Solar System"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909940983,
    title: "medium / red / Saturn",
    option1: "medium",
    option2: "red",
    option3: "Saturn",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - medium / red / Saturn",
    public_title: "medium / red / Saturn",
    options: ["medium", "red", "Saturn"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028909973751,
    title: "large / green / Moon",
    option1: "large",
    option2: "green",
    option3: "Moon",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - large / green / Moon",
    public_title: "large / green / Moon",
    options: ["large", "green", "Moon"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910006519,
    title: "large / green / Galaxy",
    option1: "large",
    option2: "green",
    option3: "Galaxy",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - large / green / Galaxy",
    public_title: "large / green / Galaxy",
    options: ["large", "green", "Galaxy"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910039287,
    title: "large / green / Solar System",
    option1: "large",
    option2: "green",
    option3: "Solar System",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - large / green / Solar System",
    public_title: "large / green / Solar System",
    options: ["large", "green", "Solar System"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910072055,
    title: "large / green / Saturn",
    option1: "large",
    option2: "green",
    option3: "Saturn",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - large / green / Saturn",
    public_title: "large / green / Saturn",
    options: ["large", "green", "Saturn"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910104823,
    title: "large / yellow / Moon",
    option1: "large",
    option2: "yellow",
    option3: "Moon",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - large / yellow / Moon",
    public_title: "large / yellow / Moon",
    options: ["large", "yellow", "Moon"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910137591,
    title: "large / yellow / Galaxy",
    option1: "large",
    option2: "yellow",
    option3: "Galaxy",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - large / yellow / Galaxy",
    public_title: "large / yellow / Galaxy",
    options: ["large", "yellow", "Galaxy"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910170359,
    title: "large / yellow / Solar System",
    option1: "large",
    option2: "yellow",
    option3: "Solar System",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - large / yellow / Solar System",
    public_title: "large / yellow / Solar System",
    options: ["large", "yellow", "Solar System"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910203127,
    title: "large / yellow / Saturn",
    option1: "large",
    option2: "yellow",
    option3: "Saturn",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - large / yellow / Saturn",
    public_title: "large / yellow / Saturn",
    options: ["large", "yellow", "Saturn"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910235895,
    title: "large / red / Moon",
    option1: "large",
    option2: "red",
    option3: "Moon",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - large / red / Moon",
    public_title: "large / red / Moon",
    options: ["large", "red", "Moon"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910268663,
    title: "large / red / Galaxy",
    option1: "large",
    option2: "red",
    option3: "Galaxy",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - large / red / Galaxy",
    public_title: "large / red / Galaxy",
    options: ["large", "red", "Galaxy"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910301431,
    title: "large / red / Solar System",
    option1: "large",
    option2: "red",
    option3: "Solar System",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: true,
    name: "1080p FreeFlow Projector - large / red / Solar System",
    public_title: "large / red / Solar System",
    options: ["large", "red", "Solar System"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028910334199,
    title: "large / red / Saturn",
    option1: "large",
    option2: "red",
    option3: "Saturn",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - large / red / Saturn",
    public_title: "large / red / Saturn",
    options: ["large", "red", "Saturn"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  {
    id: 45028915249399,
    title: "Extra large / Brown / Solar",
    option1: "extra large",
    option2: "Brown",
    option3: "Solar",
    sku: "",
    requires_shipping: true,
    taxable: false,
    featured_image: null,
    available: false,
    name: "1080p FreeFlow Projector - extra large / Brown / Solar",
    public_title: "extra large / Brown / Solar",
    options: ["extra large", "Brown", "Solar"],
    price: 1499900,
    weight: 0,
    compare_at_price: 1599900,
    inventory_management: "shopify",
    barcode: "",
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
];
export { options, variant };

// ${
//     selectedVariant[optionName] === value && "variant-selected"
//   }

// const isOptionAvailable = (ind) => {
//   const selectedOption = variant[0].options;
//   selectedOption[ind] = "";
//   const newTitle = selectedOption.join(" / ");
//   return variant.find((variant) => variant.title === newTitle && variant.available);
// };
